name: Test deployment

on:
  pull_request:
    branches: [master]
    paths: [./**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
          cache: yarn
          cache-dependency-path: ./yarn.lock
      - name: Test build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          yarn install --frozen-lockfile
          yarn build
